### ISSUE TITLE
Repetition in CSS font family

### ISSUE THREAD

**Issue by farishkash** [jonboyle/prj-rev-bwfs-dasmoto#2]
https://github.com/jonboyle/prj-rev-bwfs-dasmoto/blob/1b8996f2285fd468a6ba35797d70e6b431cef99d/Dasmotos/resources/style.css#L12

Your already using font family in the body.  There is no need to type the style in the other elements as this is being inherited.

In the screenshot below you will see the style from the body tag crossed and being replaced by the exact same style in the strong tag.

![das2](https://user-images.githubusercontent.com/5844161/41830558-a24155aa-77f6-11e8-98fc-a664863a2b95.png)

**Comment by jonboyle** [comment]
Thank you, I stuck with the font family in the body and removed from the other elements.
